Accounts fix pending
dominant-strategies/quai-snap pull request #68
Opened 2022-11-02 15:28 UTC by DenisIvanov26

Updated and fixed account methods

2022-11-02 15:46 UTC, alanorwick requested changes

2022-11-02 15:51 UTC, skunal8197 commented on testingResources/keyPairTestConstants.js
> +export const testNewBip44Entropy = {
Sorry this is an unused test file that was added as part of my merge into Denis' branch. This file will change as I make progress on unit testing

2022-11-02 15:55 UTC, skunal8197 requested changes

2022-11-02 15:55 UTC, skunal8197 commented on src/accounts.js
> +      console.log(storedAccounts);
Do we need these logs

2022-11-02 15:55 UTC, skunal8197 commented on src/accounts.js
> +          const Account = await this.generateAccount(tempAccount.path);
I'd keep variable names lowercased

2022-11-02 15:55 UTC, skunal8197 commented on src/accounts.js
> +        console.log('this.currentAccount', addr, this.currentAccount);
remove log

2022-11-02 15:55 UTC, skunal8197 commented on src/accounts.js
> +    console.log(this.accounts);
remove log

2022-11-02 15:55 UTC, skunal8197 commented on src/accounts.js
> +    console.log('context: ', context);
remove log

2022-11-02 15:56 UTC, skunal8197 commented
A few call-outs
1. Testing for these changes will be done manually in accordance to [this list of functional tests](
https://www.notion.so/dominantstrategies/6-Functional-Testing-4bb4190044b74e98a4d00a136c410d9f) using the snap's frontend interface
2. The testing files that were added in this PR are a WIP and will change as we make progress on unit testing

2022-11-03 18:43 UTC, skunal8197 commented
#69 has all these changes + more so I am closing this

2022-11-03 18:43 UTC, closed without merging