deleteAccount() and bugfixes
dominant-strategies/quai-snap pull request #77
Opened 2022-11-09 17:25 UTC by DenisIvanov26

2022-11-10 18:44 UTC, skunal8197 approved these changes
Changes for deleteAccount look good. The rest of the changes are picked up by rebasing from main

2022-11-10 20:56 UTC, alanorwick requested changes
Need to fix linter.

2022-11-11 18:36 UTC, alanorwick requested changes

2022-11-11 20:06 UTC, skunal8197 approved these changes

2022-11-11 20:10 UTC, alanorwick requested changes

2022-11-11 20:10 UTC, alanorwick commented on index.html
> +      console.log(response)
still logging response

2022-11-11 20:17 UTC, DenisIvanov26 commented on index.html
> +      console.log(response)
Remopved all logging statements

2022-11-14 18:48 UTC, alanorwick approved these changes

2022-11-14 18:48 UTC, merged